"""Constants Module"""

TBA_BASE = "https://www.thebluealliance.com/api/v3"
SCOUTING_DATABASE_URL = "https://api2.lanzersys.com/scouting/raw/matches"
SCOUTING_DATABASE_FILENAME = "full_scouting_database.csv"
PITS_DATABASE_URL = "https://api2.lanzersys.com/scouting/raw/pits"
PITS_DATABASE_FILENAME = "full_pits_database.csv"
GOOGLE_SERVICE_FILE = "scouting-416713-741bac7a780a.json"
GOOGLE_SHARED_DRIVE_ID = "0AFHrVu_BgFJ1Uk9PVA"
GOOGLE_PICKLIST_SUMMARY = "Picklist Summary"
GOOGLE_MATCH_PLANNING_SUMMARY = "Match Planning"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/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"
